theme = "dracula"

[editor]
mouse = false
cursorline = true
cursorcolumn = true
bufferline = "always"
# bufferline = "multiple"
true-color = true

[editor.statusline]
separator = ">"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "read-only-indicator", "file-modification-indicator", "separator"]
center = ["spinner", "version-control", "file-name", "diagnostics", "separator"]
right = ["selections", "register", "position", "file-encoding", "file-type"]
# default
# right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.cursor-shape]
# select = "underline"

[editor.lsp]
display-messages = true
# 是否显示变量类型
# display-inlay-hints = true 

[editor.whitespace]
render = "all"

[keys.normal]
"A-S-down" = "goto_definition"
"A-S-right" = "jump_forward"
"A-S-left" = "jump_backward"
"C-p" = "file_picker_in_current_directory"
"C-b" = "buffer_picker"
"C-f" = "search"
"A-left" = "goto_previous_buffer"
"A-right" = "goto_next_buffer"
"C-j" = "jumplist_picker"
"C-right" = "move_next_word_start"
"C-left" = "move_prev_word_start"
F12 = "hover"
"S-F12" = "goto_reference"
"C-s" = ":w"
"C-q" = ":bc"
 
[keys.insert]
"A-S-down" = "goto_definition"
"A-S-right" = "jump_forward"
"A-S-left" = "jump_backward"
"C-p" = "file_picker_in_current_directory"
"C-b" = "buffer_picker"
"C-f" = "search"
"A-left" = "goto_previous_buffer"
"A-right" = "goto_next_buffer"
# "C-j" = "jumplist_picker"
"C-z" = "undo"
"C-S-z" = "redo"
# "C-v" = "paste_after"
"C-right" = "move_next_word_start"
"C-left" = "move_prev_word_start"
F12 = "hover"
"S-F12" = "goto_reference"
"F2" = "rename_symbol"
"C-s" = ["normal_mode", ":w"]
