[font]
normal = { family = "Fira Code", style = "Retina" }
# normal = { family = "FiraCode Nerd Font" }
size = 10

[window]
# startup_mode = "Fullscreen"
startup_mode = "Maximized"

# 去除标题栏以及标题栏上的按钮(隐藏窗口按钮，最大化按钮，删除按钮)
decorations = "None" 
# option_as_alt = "OnlyLeft"


[scrolling]
history = 30000

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "l" },
# { key = "T", mods = "Control|Shift", action = "CreateNewTab" }
{ key = "N", mods = "Control|Alt", action = "SpawnNewInstance" },
{ key = "F11", action = "ToggleFullscreen" },
{ key = "W", mods = "Control|Shift", action = "Quit" }
]

# CreateNewWindow 和 SpawnNewInstance 是有区别的
# 前者的窗口属于同一个进程，后者是不同的进程

# [terminal]
# osc52 = "CopyPaste"
